external_components:
  - source: github://EspMeshMesh/esphome-meshmesh@main
    components: [meshmesh, meshmesh_direct, network, socket, esphome]

esphome:
  name: coordinator32
  friendly_name: Coordinator32
  comment: Coordinator with a Wroom32 board

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 0

api:
  reboot_timeout: 0s

# Coordinator can be always updated via serial port.
#ota:
#  platform: esphome

meshmesh:
  baud_rate: 460800
  rx_buffer_size: 2048
  tx_buffer_size: 4096
  password: !secret meshmesh_password
  channel: 3

socket:
  implementation: meshmesh_esp8266

mdns:
  disabled: True

