external_components:
  - source: github://EspMeshMesh/esphome-meshmesh@main
    components: [meshmesh, meshmesh_direct, network, socket, esphome]

preferences:
    flash_write_interval: 30sec

substitutions:
  remote_node_addr: 0x1C880F
  remote_switch_hash: 0x0642

esphome:
  name: testmesh
  friendly_name: Test Mesh
  comment: Test Node with a D1 Mini Pro board

esp8266:
  board: d1_mini_lite
  restore_from_flash : True
  framework:
    version: 3.1.2

logger:
  level: INFO
  baud_rate: 115200

api:
  reboot_timeout: 0s

ota:
  platform: meshmesh
  port: 3232

socket:
  implementation: meshmesh_esp8266

mdns:
  disabled: True

meshmesh:
  baud_rate: 0
  rx_buffer_size: 0
  tx_buffer_size: 0
  password: !secret meshmesh_password
  channel: 3
  bonding_mode: True

meshmesh_direct:
  id: meshmesh_direct_id
  on_receive:
    then:
      - lambda: |-
            ESP_LOGD("lambda", "on_receive %06X data %s", from,  format_hex_pretty(data, size).c_str());

packet_transport:
  platform: meshmesh
  update_interval: 5s
  address: 0xAABBCCDD

switch:
  - platform: gpio
    pin: D4
    name: "Blue LEDS"
    on_state:
      then:
        - lambda: |-
              const uint8_t data[] = {0x00, 0x01};
              id(meshmesh_direct_id)->unicastSendCustom(data, 2, ${remote_node_addr});

