external_components:
  - source: github://EspMeshMesh/esphome-meshmesh@main
    components: [meshmesh, meshmesh_direct, network, socket, esphome]

esphome:
  name: wroom32s3
  comment: test wroom32s3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 115200

api:
  reboot_timeout: 0s

ota:
  platform: meshmesh

meshmesh:
  channel: 3
  baud_rate: 0
  tx_buffer_size: 0
  password: !secret meshmesh_password

socket:
  implementation: meshmesh_esp8266

mdns:
  disabled: True

light:
  - platform: esp32_rmt_led_strip
    id: led_ww
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    #rmt_channel: 0
    chipset: ws2812
    name: "on board light"
