/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PB_MESHMESH_NODEINFO_PB_H_INCLUDED
#define PB_PB_MESHMESH_NODEINFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _pb_meshmesh_NodeInfo {
    char friendly_name[49];
    char firmware_version[17];
    char mac_address[25];
    char platform[17];
    char board[33];
    char compile_time[29];
    char lib_version[17];
    int32_t node_type;
} pb_meshmesh_NodeInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pb_meshmesh_NodeInfo_init_default        {"", "", "", "", "", "", "", 0}
#define pb_meshmesh_NodeInfo_init_zero           {"", "", "", "", "", "", "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_meshmesh_NodeInfo_friendly_name_tag   1
#define pb_meshmesh_NodeInfo_firmware_version_tag 2
#define pb_meshmesh_NodeInfo_mac_address_tag     3
#define pb_meshmesh_NodeInfo_platform_tag        4
#define pb_meshmesh_NodeInfo_board_tag           5
#define pb_meshmesh_NodeInfo_compile_time_tag    6
#define pb_meshmesh_NodeInfo_lib_version_tag     7
#define pb_meshmesh_NodeInfo_node_type_tag       8

/* Struct field encoding specification for nanopb */
#define pb_meshmesh_NodeInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   friendly_name,     1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   mac_address,       3) \
X(a, STATIC,   SINGULAR, STRING,   platform,          4) \
X(a, STATIC,   SINGULAR, STRING,   board,             5) \
X(a, STATIC,   SINGULAR, STRING,   compile_time,      6) \
X(a, STATIC,   SINGULAR, STRING,   lib_version,       7) \
X(a, STATIC,   SINGULAR, INT32,    node_type,         8)
#define pb_meshmesh_NodeInfo_CALLBACK NULL
#define pb_meshmesh_NodeInfo_DEFAULT NULL

extern const pb_msgdesc_t pb_meshmesh_NodeInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_meshmesh_NodeInfo_fields &pb_meshmesh_NodeInfo_msg

/* Maximum encoded size of messages (where known) */
#define PB_MESHMESH_NODEINFO_PB_H_MAX_SIZE       pb_meshmesh_NodeInfo_size
#define pb_meshmesh_NodeInfo_size                205

/* Message IDs (where set with "msgid" option) */
#define PB_MSG_17 pb_meshmesh_NodeInfo

#define NODEINFO_MESSAGES \
	PB_MSG(17,205,pb_meshmesh_NodeInfo) \

#define pb_meshmesh_NodeInfo_msgid 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
